version: "3.9"

services:
    go:
        build: ./go
        ports:
            - "8087:8080"
        container_name: go_api
        volumes:
            - ./go:/go_api_app
        tty: true

    react:
        build: ./react
        ports:
            - "3000:3000"
        container_name: go_react
        volumes:
            - ./react:/app
            - /app/node_modules
        tty: true
        command: sh -c "yarn && yarn start"


    db:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: go_api_prac
            MYSQL_USER: go_api_prac
            MYSQL_PASSWORD: go_api_prac
            TZ: "Asia/Tokyo"

        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306
