version: "3.9"

services:
    go:
        build: .
        ports:
        - "8081:8080"
        container_name: go_api
        volumes:
        - ./src:/go_api_app
        tty: true

    db:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: go_api_prac
            MYSQL_USER: go_api_prac
            MYSQL_PASSWORD: go_api_prac
            TZ: "Asia/Tokyo"

        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./infra/db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306
